config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'awards/:character_id', to: 'awards#show', as: :awards
  get 'missions', to: 'missions#index', as: :missions
  get 'missions/:id', to: 'missions#show', as: :mission
  get 'legal', to: 'pages#legal'
  get 'stats', to: 'pages#stats'
  get 'info', to: 'pages#info'
  get 'changes', to: 'pages#changes'
  resources :corporations

  constraints subdomain: %w[rats ratopedia rat] do
    get '/', to: 'factions#index'
  end
  get 'search', to: 'search#search'
  get 'factions', to: 'factions#index', as: :factions
  get 'factions/:id', to: 'factions#show', as: :faction
  get 'factions/:faction_id/groups/:group_id', to: 'factions#groups', as: :group
  get 'groups', to: 'factions#generic', as: :generic_groups
  get 'groups/:group_id', to: 'factions#generic_group', as: :generic_group
  get 'factions/groups'
  get 'rats/:id', to: 'rats#show', as: :rats
  get 'rats/:id/details', to: 'rats#details', as: :rats_details
  get 'welcome/index'
  get 'characters', to: 'characters#index', as: :characters
  get 'characters/:character_id', to: 'characters#profile', as: :character_profile
  get 'characters/:character_id/earnings', to: 'characters#earnings', as: :character_earnings
  get 'characters/:character_id/ticks', to: 'characters#ticks', as: :character_ticks
  get 'characters/:character_id/rats', to: 'characters#rats', as: :character_rats
  get 'characters/:character_id/journal', to: 'characters#journal', as: :character_journal
  delete 'characters/:character_id/destroy', to: 'characters#destroy', as: :character_destroy
  patch 'characters/:character_id/display_option', to: 'characters#display_option', as: :character
  get 'ticks', to: 'welcome#ticks', as: :global_ticks
  get 'ticks/:tick_id', to: 'welcome#tick', as: :global_tick
  get 'average_ticks', to: 'welcome#average_ticks', as: :average_ticks
  get 'isk', to: 'welcome#isk', as: :isk
  get 'isk_corporations', to: 'welcome#isk_corporations', as: :corporations_isk

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'welcome#index'
end

app/models/rat.rb
# frozen_string_literal: true

class Rat
  include MongoidSetup
  include ApiAttributes
  field :name, type: String
  field :bounty, type: Float
  has_and_belongs_to_many :loot, class_name: 'Loot'
  has_many :kills
  belongs_to :faction, optional: true
  belongs_to :group, optional: true
  belongs_to :ded_site, optional: true

  before_save :details_from_api, :set_faction, unless: :just_save

  scope :with_bounty, -> { where(:bounty.ne => nil).where(:bounty.gt => 0) }

  alias rat_attributes api_attributes

  attr_accessor :just_save

  def assign_bounty
    self.bounty = begin
                    api_object.dogma_attributes.select { |a| a.attribute_id == 481 }.first.try(:value)
                  rescue StandardError
                    nil
                  end
  end

  def update_bounty
    assign_bounty
    save
  end

  def details_from_api
    assign_bounty
    self.name = api_object.name
    self.group_id = api_object.group_id
  end

  def description
    types_api.description
  end

  def set_faction
    faction = Faction.detect(group.name) || Faction.detect(name)
    return false unless faction
    self.faction_id = faction.id
  end

  def structure_hitpoints
    rat_attributes.select { |a| a.id == 9 }[0]
  end

  private

  def api_object
    @api_object ||= ESI::UniverseApi.new.get_universe_types_type_id(id)
  end
end

app/controllers/rats_controller.rb
# frozen_string_literal: true

class RatsController < ApplicationController
  before_action :set_rat
  before_action :set_attributes
  before_action :set_missile_attributes, only: :show

  def show
  rescue Mongoid::Errors::DocumentNotFound
    head :not_found
  end

  def set_rat
    @rat = Rat.find(params[:id].to_i)
  end

  def set_attributes
    @attributes = begin
                    Rats::Attributes.new(@rat.rat_attributes)
                  rescue Mongoid::Errors::DocumentNotFound
                    Rats::Attributes.new({})
                  end
  end

  def set_missile_attributes
    @missile_attributes = begin
                            Charges::Attributes.new(Charge.find(@attributes.entity_missile_type_id.value.to_i).charge_attributes)
                          rescue StandardError
                            nil
                          end
  end

  def details; end
end

app/helpers/rats_helper.rb
# frozen_string_literal: true

module RatsHelper
  HP_PRESENTERS = %i[hp armor_hp shield_capacity].freeze

  HP_PRESENTERS.each do |method_name|
    define_method(method_name) do
      begin
        icon_tag(method_name.to_s, @attributes.send(method_name).display_name) + @attributes.send(method_name).presented_value
      rescue StandardError
        '-'
      end
    end
  end

  def repair(type)
    icon = icon_tag(type.to_s, "#{type.to_s.titleize} Per Second")
    rep = @attributes.repair_value(type)
    icon + number_with_precision(rep, precision: 2, delimiter: ',') + ' HP/s'
  rescue StandardError
    icon + '-'
  end

  def resistance_value(type, flavour)
    number_with_delimiter((100 - @attributes.send("#{flavour}_#{type}_damage_resonance").value * 100).to_i) + ' %'
  rescue StandardError
    '0 %'
  end

  def turret_damage(type)
    number_with_precision((@attributes.send("#{type}_damage").value * @attributes.damage_multiplier.value / (@attributes.speed.value / 1000)), precision: 2, delimiter: ',')
  rescue StandardError
    '-'
  end

  def missile_damage(type)
    begin
      multiplier = @attributes.missile_damage_multiplier.value
    rescue StandardError
      multiplier = 1
    end
    number_with_precision((@missile_attributes.send("#{type}_damage").value * multiplier / (@attributes.missile_launch_duration.value / 1000)), precision: 2, delimiter: ',')
  rescue StandardError
    '-'
  end

  def total_turret_damage
    total = @attributes.summarize_damage * @attributes.damage_multiplier.value / (@attributes.speed.value / 1000)
    icon_tag('turret', 'Turret DPS') + number_with_precision(total, precision: 2, delimiter: ',')
  rescue StandardError
    icon_tag('turret', 'Turret DPS') + '-'
  end

  def total_missile_damage
    begin
      multiplier = @attributes.missile_damage_multiplier.value
    rescue StandardError
      multiplier = 1
    end
    total = @missile_attributes.summarize_damage / (@attributes.missile_launch_duration.value / 1000) * multiplier
    icon_tag('missile_launcher', 'Missle DPS') + ' ' + number_with_precision(total, precision: 2, delimiter: ',')
  rescue StandardError
    icon_tag('missile_launcher', 'Missle DPS') + '-'
  end

  def damage_type(type, flavour)
    icon_tag("#{type}_#{flavour}", "#{type.to_s.capitalize} #{flavour.to_s.capitalize}")
  rescue StandardError
    ''
  end

  def other_effects(opts)
    text = +"<strong><em>#{opts[:title]}</em></strong><br>"
    opts[:attributes].each do |attribute|
      text << "<strong>#{attribute[:name]}:</strong> #{attribute[:value]} #{attribute[:unit]}<br>"
    end
    icon_tag(opts[:icon], text)
  rescue StandardError
    ''
  end

  EFFECT_PRESENT_HELPERS = %i[web neut scram ecm].freeze

  EFFECT_PRESENT_HELPERS.each do |method_name|
    define_method(method_name) do
      begin
        other_effects @attributes.send(method_name)
      rescue StandardError
        ''
      end
    end
  end

  SIMPLE_PRESENT_HELPERS = %i[
    max_velocity entity_cruise_speed entity_fly_range max_range signature_radius optimal_sig_radius
    max_locked_targets max_attack_targets ai_ignore_drones_below_signature_radius entity_kill_bounty
  ].freeze

  SIMPLE_PRESENT_HELPERS.each do |method_name|
    define_method(method_name) do
      begin
        @attributes.send(method_name).presented_value
      rescue StandardError
        '-'
      end
    end
  end
end

app/views/rats/details.html.haml
%ol.breadcrumb
  %li.breadcrumb-item= link_to @rat.name, rats_path(@rat)
  %li.breadcrumb-item.active Details

.panel.panel-default
  .panel-body
    %table.table.table-condensed
      %caption Hover Attribute Name cell for description
      %thead
        %tr
          %th Attribute Name
          %th Attribute Display Name
          %th Snake Case Attribute Name
          %th Value
      - @rat.rat_attributes.sort_by { |a| a.name }.each do |attribute|
        %tr
          %th
            %span{ tooltip(attribute.description).merge({style: 'cursor: pointer'}) }= attribute.name
          %td= attribute.display_name || '-'
          %td= attribute.name.underscore
          %td= attribute.value

app/views/rats/show.html.haml
%ol.breadcrumb
  %li.breadcrumb-item
    = link_to 'Factions', factions_path
  - if @rat.faction && @rat.group.faction
    %li.breadcrumb-item
      = link_to @rat.faction.name, faction_path(id: @rat.faction_id)
    %li.breadcrumb-item
      = link_to @rat.group.name, group_path(faction_id: @rat.faction_id, group_id: @rat.group_id)
  - else
    %li.breadcrumb-item
      = link_to 'Generic Groups', generic_groups_path
    %li.breadcrumb-item
      = link_to @rat.group.name, generic_group_path(group_id: @rat.group_id)
  %li.breadcrumb-item.active= @rat.name
.panel.panel-default
  .panel-body
    .row
      .col-sm-12
        %table.table.table-condensed
          %caption Description
          %tr
            %td= @rat.description.html_safe
    .row
      .col-sm-3
        %table.table.table-condensed
          %caption Image & Faction
          %tr
            %td{ rowspan: 2 }
              = type_image(@rat.id, 64, highligh_ded_boss: false)
              = faction_image(@rat.faction_id, 64)
              = ded_site?(@rat.ded_site)
        %table.table.table-condensed
          %caption Bounty
          %tr
            %td
              = icon_tag('isk')
              = entity_kill_bounty
      .col-sm-9
        %table.table.table-condensed
          %caption Defense
          %tr
            %th HP
            %th Repair
            %td= damage_type(:kinetic, :resist)
            %td= damage_type(:thermal, :resist)
            %td= damage_type(:explosive, :resist)
            %td= damage_type(:em, :resist)
          %tr
            %td.col-sm-2= shield_capacity
            %td.col-sm-2= repair(:shield_boost)
            %td.col-sm-1= resistance_value(:kinetic ,:shield)
            %td.col-sm-1= resistance_value(:thermal ,:shield)
            %td.col-sm-1= resistance_value(:explosive ,:shield)
            %td.col-sm-1= resistance_value(:em ,:shield)
          %tr
            %td= armor_hp
            %td= repair(:armor_repair)
            %td= resistance_value(:kinetic, :armor)
            %td= resistance_value(:thermal, :armor)
            %td= resistance_value(:explosive, :armor)
            %td= resistance_value(:em, :armor)
          %tr
            %td{ colspan: 6 }= hp
    .row
      .col-sm-6
        %table.table.table-condensed
          %caption Navigation & Targeting
          %tr
            %td.col-sm-3= icon_tag('ab', 'Cruise Speed') + entity_cruise_speed
            %td.col-sm-3= icon_tag('mwd', 'Max Speed') + max_velocity
            %td.col-sm-3= icon_tag('orbit', 'Orbit Range') + entity_fly_range
            %td.col-sm-3= icon_tag('range', 'Max Range') + max_range
          %tr
            %td= icon_tag('sig', 'Signature Radius') + signature_radius
            %td= icon_tag('sig', 'Prefered Target Signature Radius') + optimal_sig_radius
            %td= icon_tag('target', 'Max Locked Targets') + max_locked_targets
            %td= icon_tag('target', 'Max Targets') + max_attack_targets
          %tr
            %td{ colspan: 4}= icon_tag('drones', 'Ignore Drones Below This Size') + ai_ignore_drones_below_signature_radius
        
      .col-sm-6
        %table.table.table-condensed
          %caption Offense
          %tr
            %th DPS
            %td= damage_type(:kinetic, :damage)
            %td= damage_type(:thermal, :damage)
            %td= damage_type(:explosive, :damage)
            %td= damage_type(:em, :damage)
          %tr
            %td.col-sm-1= total_turret_damage
            %td.col-sm-1= turret_damage(:kinetic)
            %td.col-sm-1= turret_damage(:thermal)
            %td.col-sm-1= turret_damage(:explosive)
            %td.col-sm-1= turret_damage(:em)
          %tr
            %td= total_missile_damage
            %td= missile_damage(:kinetic)
            %td= missile_damage(:thermal)
            %td= missile_damage(:explosive)
            %td= missile_damage(:em)
    .row
      .col-sm-12
        %table.table.table-condensed
          %caption EWAR
          %tr
            %td
              = scram
              = web
              = neut
              = ecm
    - unless @rat.loot.empty?
      .row
        .col-sm-12
          %table.table.table-condensed
            %caption 
              Loot
            %tr
              %th
              %th Item Name
              %th.numeric Average Price
            - @rat.loot.sort_by { |l| l.name }.each do |item|
              %tr
                %td= type_image(item.id)
                %td= item.name
                %td.numeric= item.price ? number_with_precision(item.price, precision: 2, delimiter: ',') + ' ISK' : '-'
        
    .row
      .col-sm-12
        = link_to 'More Details', rats_details_path(@rat), class: 'btn btn-primary'