config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'awards/:character_id', to: 'awards#show', as: :awards
  get 'missions', to: 'missions#index', as: :missions
  get 'missions/:id', to: 'missions#show', as: :mission
  get 'legal', to: 'pages#legal'
  get 'stats', to: 'pages#stats'
  get 'info', to: 'pages#info'
  get 'changes', to: 'pages#changes'
  resources :corporations

  constraints subdomain: %w[rats ratopedia rat] do
    get '/', to: 'factions#index'
  end
  get 'search', to: 'search#search'
  get 'factions', to: 'factions#index', as: :factions
  get 'factions/:id', to: 'factions#show', as: :faction
  get 'factions/:faction_id/groups/:group_id', to: 'factions#groups', as: :group
  get 'groups', to: 'factions#generic', as: :generic_groups
  get 'groups/:group_id', to: 'factions#generic_group', as: :generic_group
  get 'factions/groups'
  get 'rats/:id', to: 'rats#show', as: :rats
  get 'rats/:id/details', to: 'rats#details', as: :rats_details
  get 'welcome/index'
  get 'characters', to: 'characters#index', as: :characters
  get 'characters/:character_id', to: 'characters#profile', as: :character_profile
  get 'characters/:character_id/earnings', to: 'characters#earnings', as: :character_earnings
  get 'characters/:character_id/ticks', to: 'characters#ticks', as: :character_ticks
  get 'characters/:character_id/rats', to: 'characters#rats', as: :character_rats
  get 'characters/:character_id/journal', to: 'characters#journal', as: :character_journal
  delete 'characters/:character_id/destroy', to: 'characters#destroy', as: :character_destroy
  patch 'characters/:character_id/display_option', to: 'characters#display_option', as: :character
  get 'ticks', to: 'welcome#ticks', as: :global_ticks
  get 'ticks/:tick_id', to: 'welcome#tick', as: :global_tick
  get 'average_ticks', to: 'welcome#average_ticks', as: :average_ticks
  get 'isk', to: 'welcome#isk', as: :isk
  get 'isk_corporations', to: 'welcome#isk_corporations', as: :corporations_isk

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'welcome#index'
end

app/views/shared/_alerts.html.haml
- flash.each do |flash|
  = flash_to_alert flash

app/views/shared/_breadcrumbs.html.haml
%ol.breadcrumb
  - crumbs.each do |crumb|
    - if crumbs.last == crumb
      %li.breadcrumb-item.active= crumb
    - else
      %li.breadcrumb-item
        = crumb

app/views/shared/_footer.html.haml
%footer
  .text-muted 
    %em "Out here progress is numbers..."
    All 
    = link_to 'EVE related materials', legal_path
    are property of 
    = link_to 'CCP Games', 'https://www.ccpgames.com'
    = ', © EVESCORE'
    = Time.now.year
    = link_to 'Changes', changes_path
    

app/views/shared/_navbar.html.haml
%nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => "/"}
        = image_tag 'evescore.png'
    %ul.nav.navbar-nav
      %li
      %li.dropdown
        %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
          Menu
          %span.caret
        %ul.dropdown-menu
          %li= link_to 'Welcome Page', welcome_path
          %li= link_to 'Factions', factions_path
          %li= link_to 'Corporations', corporations_path
          %li= link_to 'Missions', missions_path if current_user
    %ul.nav.navbar-nav.pull-right
      %li.navbar-form
        .form-group
          %input{type: :text, class: 'form-control typeahead', id: 'search', placeholder: 'Search', autocomplete: 'off'}
      - if current_user
        - current_user.characters.each do |character|
          %li= link_to navbar_portrait(character), character_profile_path(character)
        %li
          = link_to icon('user'), characters_path
        %li
          = link_to icon('log-out'), destroy_user_session_path, method: :delete
      - else
        %li
          = link_to icon('log-in'), new_user_session_path

app/views/shared/_top_table.html.haml
%table.table.table-striped
  = top_table_caption(caption, more ||= false)
  = top_table_head(subject, value)
  %tbody
    - top_table.each do |record|
      = top_table_row(record, subject_image_link: subject_image_link, subject_field: subject_field, value_field: value_field, subject_link: subject_link, value_display: value_display)