config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'awards/:character_id', to: 'awards#show', as: :awards
  get 'missions', to: 'missions#index', as: :missions
  get 'missions/:id', to: 'missions#show', as: :mission
  get 'legal', to: 'pages#legal'
  get 'stats', to: 'pages#stats'
  get 'info', to: 'pages#info'
  get 'changes', to: 'pages#changes'
  resources :corporations

  constraints subdomain: %w[rats ratopedia rat] do
    get '/', to: 'factions#index'
  end
  get 'search', to: 'search#search'
  get 'factions', to: 'factions#index', as: :factions
  get 'factions/:id', to: 'factions#show', as: :faction
  get 'factions/:faction_id/groups/:group_id', to: 'factions#groups', as: :group
  get 'groups', to: 'factions#generic', as: :generic_groups
  get 'groups/:group_id', to: 'factions#generic_group', as: :generic_group
  get 'factions/groups'
  get 'rats/:id', to: 'rats#show', as: :rats
  get 'rats/:id/details', to: 'rats#details', as: :rats_details
  get 'welcome/index'
  get 'characters', to: 'characters#index', as: :characters
  get 'characters/:character_id', to: 'characters#profile', as: :character_profile
  get 'characters/:character_id/earnings', to: 'characters#earnings', as: :character_earnings
  get 'characters/:character_id/ticks', to: 'characters#ticks', as: :character_ticks
  get 'characters/:character_id/rats', to: 'characters#rats', as: :character_rats
  get 'characters/:character_id/journal', to: 'characters#journal', as: :character_journal
  delete 'characters/:character_id/destroy', to: 'characters#destroy', as: :character_destroy
  patch 'characters/:character_id/display_option', to: 'characters#display_option', as: :character
  get 'ticks', to: 'welcome#ticks', as: :global_ticks
  get 'ticks/:tick_id', to: 'welcome#tick', as: :global_tick
  get 'average_ticks', to: 'welcome#average_ticks', as: :average_ticks
  get 'isk', to: 'welcome#isk', as: :isk
  get 'isk_corporations', to: 'welcome#isk_corporations', as: :corporations_isk

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'welcome#index'
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  before_action :top_isk, only: :index
  before_action :top_ticks, only: :index
  before_action :top_average_ticks, only: :index
  before_action :total_isk, only: :index
  before_action :total_tax, only: :index
  before_action :total_kills, only: :index
  before_action :total_ded_sites, only: :index
  before_action :total_missions, only: :index
  before_action :corporations_top_isk, only: :index
  before_action :corporations_top_tax, only: :index
  before_action :public_top_ded_sites, only: :index
  before_action :public_top_missions, only: :index
  before_action :public_top_kills, only: :index

  DEFAULT_PER_PAGE = 10

  def index; end

  def ticks
    @top_ticks = WalletRecord.public_top_ticks.top_ticks.page(params[:page]).per(DEFAULT_PER_PAGE)
  end

  def average_ticks
    @top_average_ticks = Kaminari.paginate_array(WalletRecord.public_top_average_ticks.to_a).page(params[:page]).per(DEFAULT_PER_PAGE)
  end

  def isk
    @top_isk = Kaminari.paginate_array(WalletRecord.public_top_isk.to_a).page(params[:page]).per(DEFAULT_PER_PAGE)
  end

  def isk_corporations
    @corporations_top_isk = Kaminari.paginate_array(WalletRecord.corporations_top_isk.to_a).page(params[:page]).per(DEFAULT_PER_PAGE)
  end

  def tick
    @tick = WalletRecord.public_records.find(params[:tick_id])
  end

  private

  def top_isk
    @top_isk = WalletRecord.public_top_isk(5)
  end

  def top_ticks
    @top_ticks = WalletRecord.public_top_ticks.top_ticks.limit(5)
  end

  def top_average_ticks
    @top_average_ticks = WalletRecord.public_top_average_ticks(5)
  end

  def total_isk
    @total_isk = WalletRecord.all.sum(:amount)
  end

  def total_tax
    @total_tax = WalletRecord.all.sum(:tax)
  end

  def total_kills
    @total_kills = Kill.all.sum(:amount)
  end

  def total_ded_sites
    @total_ded_sites = WalletRecord.where(:ded_site.ne => nil).count
  end

  def total_missions
    @total_missions = WalletRecord.where(:mission_level.ne => nil).count
  end

  def corporations_top_isk
    @corporations_top_isk = WalletRecord.corporations_top_isk(5)
  end

  def corporations_top_tax
    @corporations_top_tax = WalletRecord.corporations_top_tax(5)
  end

  def public_top_ded_sites
    @public_top_ded_sites = WalletRecord.public_top_ded_sites
  end

  def public_top_missions
    @public_top_missions = WalletRecord.public_top_missions(5)
  end

  def public_top_kills
    @public_top_kills = Kill.public_top(5)
  end
end

app/views/welcome/_global_summary.html.haml
%table.table.table-striped
  %caption
    Global
  %thead
    %tr
      %th.icon
      %th Feat
      %th.numeric Value
  %tbody
    %tr
      %td= isk_image
      %td Total ISK
      %td.numeric= number_to_isk @total_isk
    %tr
      %td= isk_image
      %td Total Tax
      %td.numeric= number_to_isk @total_tax
    %tr
      %td= icon_tag(:skull)
      %td Total Kills
      %td.numeric= number_with_delimiter @total_kills
    %tr
      %td= corporation_image(1000137)
      %td DED Sites Completed
      %td.numeric= number_with_delimiter @total_ded_sites
    %tr
      %td= icon_tag(:lp)
      %td Missions Completed
      %td.numeric= number_with_delimiter @total_missions

app/views/welcome/average_ticks.html.haml
= breadcrumbs welcome_page_link, 'Top Average Ticks'
= top_table(@top_average_ticks, caption: 'Top 5 Average Ticks', more: global_ticks_path, subject_field: '_id')
= paginate @top_average_ticks

app/views/welcome/index.html.haml
.row
  .col-sm-4
    = top_table(@top_isk, caption: 'Top 5 Total ISK Earned', more: isk_path, subject_field: '_id')
  .col-sm-4
    = top_table(@top_ticks, caption: 'Top 5 Ticks', more: global_ticks_path, subject_field: 'character_id')
  .col-sm-4
    = top_table(@top_average_ticks, caption: 'Top 5 Average Ticks', more: average_ticks_path, subject_field: '_id')
.row
  .col-sm-4
    = render :partial => 'global_summary'
  .col-sm-4
    = top_table(@corporations_top_isk, caption: 'Top 5 Total ISK Earned (Corporations)', subject_field: '_id', subject: :corporation)
  .col-sm-4
    = top_table(@corporations_top_tax, caption: 'Top 5 Total Tax Collected (Corporations)', value_field: 'tax', subject_field: '_id', subject: :corporation)
.row
  .col-sm-4
    = top_table(@public_top_ded_sites, caption: 'Top 5 Total DED Sites Completed', more: false, value_field: 'count', subject_field: '_id', value_display: :number_with_delimiter)
  .col-sm-4
    = top_table(@public_top_missions, caption: 'Top 5 Total Missions Completed', more: false, value_field: 'count', subject_field: '_id', value_display: :number_with_delimiter)
  .col-sm-4
    = top_table(@public_top_kills, caption: 'Top 5 Total Rat Kills', more: false, subject_field: '_id', value_display: :number_with_delimiter)

app/views/welcome/isk.html.haml
= breadcrumbs welcome_page_link, 'Top ISK'
= top_table(@top_isk, caption: 'Top 5 Total ISK Earned', more: isk_path, subject_field: '_id')
= paginate @top_isk

app/views/welcome/isk_corporations.html.haml
= breadcrumbs welcome_page_link, 'Top ISK Earned (Corporations)'
= render partial: 'top_isk_corporations', locals: { caption: 'Top ISK Earned  (Corporations)' }
= paginate @corporations_top_isk

app/views/welcome/tick.html.haml
= breadcrumbs welcome_page_link, character_link(@tick.character), character_ticks_link(@tick.character), @tick.ts

.panel.panel-default
  .panel-heading
    .row
      .col-sm-2
        = character_image_link(@tick.character_id, 64)
        = corporation_image_link(@tick.character.corporation, 64)
      .col-sm-4
        = character_link @tick.character
        %br
        = corporation_link @tick.character.corporation
        %br
        = @tick.ts
      .col-sm-2.numeric
        GROSS AMOUNT
        %h4=number_to_isk @tick.tax + @tick.amount
      .col-sm-2.numeric
        TAX
        %h4=number_to_isk @tick.tax
      .col-sm-2.numeric
        NET AMOUNT
        %h4=number_to_isk @tick.amount
  .panel-body
    - if @tick.type != 'bounty_prizes'
      = record_icon(@tick, 64)
      = record_details(@tick)
    - if !@tick.kills.empty?
      %table.table.table-condensed
        %tr
          %th Amount
          %th Rat Name
          %th Group Name
          %th.numeric Bounty
        - @tick.kills.each do |kill|
          %tr
            %td= kill.amount
            %td
              = rat_image_link(kill.rat.id)
              &nbsp;
              = rat_link kill.rat
            %td
              = group_link kill.rat.group
            %td.numeric
              = number_to_isk kill.rat.bounty
        %tr
          %th 
          %th
          %th.numeric
            NET
            = number_to_isk @tick.amount
          %th.numeric= number_to_isk @tick.kills.map { |k| k.rat.bounty * k.amount }.sum
              
      

app/views/welcome/ticks.html.haml
= breadcrumbs welcome_page_link, 'Top Ticks'
= top_table(@top_ticks, caption: 'Top 5 Ticks', more: global_ticks_path, subject_field: 'character_id')
= paginate @top_ticks