config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'awards/:character_id', to: 'awards#show', as: :awards
  get 'missions', to: 'missions#index', as: :missions
  get 'missions/:id', to: 'missions#show', as: :mission
  get 'legal', to: 'pages#legal'
  get 'stats', to: 'pages#stats'
  get 'info', to: 'pages#info'
  get 'changes', to: 'pages#changes'
  resources :corporations

  constraints subdomain: %w[rats ratopedia rat] do
    get '/', to: 'factions#index'
  end
  get 'search', to: 'search#search'
  get 'factions', to: 'factions#index', as: :factions
  get 'factions/:id', to: 'factions#show', as: :faction
  get 'factions/:faction_id/groups/:group_id', to: 'factions#groups', as: :group
  get 'groups', to: 'factions#generic', as: :generic_groups
  get 'groups/:group_id', to: 'factions#generic_group', as: :generic_group
  get 'factions/groups'
  get 'rats/:id', to: 'rats#show', as: :rats
  get 'rats/:id/details', to: 'rats#details', as: :rats_details
  get 'welcome/index'
  get 'characters', to: 'characters#index', as: :characters
  get 'characters/:character_id', to: 'characters#profile', as: :character_profile
  get 'characters/:character_id/earnings', to: 'characters#earnings', as: :character_earnings
  get 'characters/:character_id/ticks', to: 'characters#ticks', as: :character_ticks
  get 'characters/:character_id/rats', to: 'characters#rats', as: :character_rats
  get 'characters/:character_id/journal', to: 'characters#journal', as: :character_journal
  delete 'characters/:character_id/destroy', to: 'characters#destroy', as: :character_destroy
  patch 'characters/:character_id/display_option', to: 'characters#display_option', as: :character
  get 'ticks', to: 'welcome#ticks', as: :global_ticks
  get 'ticks/:tick_id', to: 'welcome#tick', as: :global_tick
  get 'average_ticks', to: 'welcome#average_ticks', as: :average_ticks
  get 'isk', to: 'welcome#isk', as: :isk
  get 'isk_corporations', to: 'welcome#isk_corporations', as: :corporations_isk

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'welcome#index'
end

app/models/character.rb
# frozen_string_literal: true

class Character
  include MongoidSetup
  include EsiCharacterApi
  include ProfileStats
  field :name, type: String
  field :access_token, type: String
  field :refresh_token, type: String
  field :token_expires, type: Time
  field :display_option, type: String
  belongs_to :corporation, optional: true, counter_cache: true
  belongs_to :alliance, optional: true, counter_cache: true
  belongs_to :user, counter_cache: true
  has_many :wallet_records
  has_many :kills
  has_many :character_awards

  scope :public_characters, -> { where(display_option: 'Public') }
  scope :without_test, -> { where(:id.nin => TEST_CHARS) }

  after_save :create_corporation
  after_create :queue_initial_import

  def award?(award_id)
    character_awards.where(award_id: award_id).first || false
  end

  def awards
    character_awards.map(&:award)
  end

  def queue_initial_import
    CharacterWalletImportJob.perform_later(self)
  end

  def create_corporation
    Corporation.create_from_api(corporation_id)
  end

  def wallet_journal
    wallet_api.get_characters_character_id_wallet_journal(id)
  end

  def import_wallet
    wallet_journal.select { |r| WalletRecord.importable?(r.ref_type) }.each do |wallet_record|
      WalletRecord.create_from_api(id, user_id, wallet_record)
    end
  end

  def grant_awards
    Award.all.each do |award|
      AwardService.new(self, award).check
    end
  end

  def faction_rat_kills(faction_id)
    kills.where(:rat_id.in => Rat.where(:group_id.in => Faction.find(faction_id).groups.where(name: /Commander/).map(&:id)).map(&:id))
  end
end

app/controllers/characters_controller.rb
# frozen_string_literal: true

class CharactersController < AuthController
  before_action :set_character, except: :index
  skip_before_action :authenticate_user!, if: :character_public?
  before_action :check_owner, unless: :character_public?, except: :index

  DEFAULT_PER_PAGE = 10

  def index
    @characters = current_user.characters || []
  end

  def profile
    @ticks = @character.wallet_records.order('ts desc').limit(5)
    @earnings_by_day = @character.earnings_by_day(5)
    @valuable_rats = @character.kills_by_bounty(5)
    @top_ticks = @character.wallet_records.top_ticks.limit(5)
  end

  def earnings
    @earnings_by_day = Kaminari.paginate_array(@character.earnings_by_day.to_a).page(params[:page]).per(DEFAULT_PER_PAGE)
  end

  def ticks
    @top_ticks = @character.wallet_records.order('amount desc').page(params[:page]).per(DEFAULT_PER_PAGE)
  end

  def rats
    @valuable_rats = Kaminari.paginate_array(@character.kills_by_bounty.to_a).page(params[:page]).per(DEFAULT_PER_PAGE)
  end

  def journal
    @ticks = @character.wallet_records.order('ts desc').page(params[:page]).per(DEFAULT_PER_PAGE)
  end

  def destroy
    @character.destroy
    redirect_to characters_path, notice: 'Character removed'
  end

  def display_option
    redirect_to characters_path, alert: 'Something went wrong with display option change' && return unless @character.update(character_params)
    redirect_to characters_path, notice: "Display option for #{@character.name} now set to #{character_params[:display_option]}"
  end

  protected

  def check_owner
    current_user.characters.include?(@character) || redirect_to(root_path, notice: "You don't have access to this character")
  end

  def set_character
    @character = Character.find(params[:character_id].to_i)
  end

  def character_params
    params.require(:character).permit(:display_option)
  end

  def character_public?
    return if params[:action] == 'index'
    set_character.display_option == 'Public'
  end
end

app/views/characters/_character.html.haml
%tr
  %td
    = link_to character_image(character.id), character_profile_path(character.id)
    = corporation_image(character.corporation_id, 64)
    = character.alliance ? alliance_image(character.alliance_id, 64) : nil
  %td= link_to character.name, character_profile_path(character.id)
  %td= character.corporation.name
  %td= character.alliance ? character.alliance.name : '-'
  %td
    = form_for character do |f|
      = f.select :display_option, [ 'Private', 'Public' ], {}, { class: 'selectpicker' }
      = f.submit 'Set', class: 'btn btn-success'
  %td
    = link_to 'Delete', character_destroy_path(character.id), method: :delete, class: 'btn btn-danger pull-right', data: { confirm: 'Are you sure?' }

app/views/characters/_earnings_by_day.html.haml
%table.table.table-striped
  %caption
    = caption || ''
    - more ||= false
    - if more
      %span.pull-right= link_to 'More', character_earnings_path(@character)
  %thead
    %tr
      %th.icon
      %th Date
      %th.numeric Amount
  %tbody
    - @earnings_by_day.each do |record|
      %tr
        %td= isk_image
        %td= record['date'].to_date.to_s
        %td.numeric= number_to_isk record['amount']

app/views/characters/_ticks.html.haml
%table.table.table-striped
  %caption
    = caption ||= ''
    - more ||= false
    - if more 
      %span.pull-right= link_to 'More', character_journal_path(@character)
    
  %thead
    %tr
      %th.icon
      %th.timestamp Timestamp
      %th.details Details
      %th
      %th.numeric Amount
  %tbody
    - @ticks.each do |record|
      %tr
        %td= record_icon(record)
        %td
          = link_to record.ts, global_tick_path(record)
        %td= record_details(record)
        %td
          - record.kills.each do |kill|
            = kill_image(kill)
        %td.numeric{ nowrap: :nowrap }= number_to_isk record.amount

app/views/characters/_top_ticks.html.haml
%table.table.table-striped
  %caption
    = caption || ''
    - more ||= false
    - if more
      %span.pull-right= link_to 'More', character_ticks_path(@character)
  %thead
    %tr
      %th.icon
      %th Timestamp
      %th.numeric Amount
  %tbody
    - @top_ticks.each do |record|
      %tr
        %td= record_icon(record)
        %td= link_to record.ts, global_tick_path(record)
        %td.numeric= number_to_isk record.amount

app/views/characters/_valuable_rats.html.haml
%table.table.table-striped
  %caption
    Top 5 Rats Bounty
    - more || false
    - if more
      %span.pull-right= link_to 'More', character_rats_path(@character)
  %thead
    %tr
      %th.icon
      %th Rat Name
      %th.numeric Bounty
  %tbody
    - @valuable_rats.each do |record|
      %tr
        %td= kill_image(record)
        %td= link_to record['name'], rats_path(record['rat_id'])
        %td.numeric= number_to_isk_short record['bounty']

app/views/characters/earnings.html.haml
%p#notice= notice

= breadcrumbs welcome_page_link, character_link(@character), 'Earnings'
= render partial: 'earnings_by_day', locals: { caption: 'Earnings' }
= paginate @earnings_by_day

app/views/characters/index.html.haml
%table.table.table-striped
  %caption
    To add characters click
    \#{login_with_eve}
    and select the character you wish to add
  - if current_user.characters.count == 0
  - else  
    %thead
      %tr
        %th
        %th Name
        %th Corporation Name
        %th Alliance Name
        %th Display Option
        %th
    %tbody
      - @characters.each do |character|
        = render partial: 'character', object: character

app/views/characters/journal.html.haml
%p#notice= notice
= breadcrumbs welcome_page_link, character_link(@character), 'Ticks Journal'
= render :partial => 'ticks', locals: { caption: 'Ticks Journal'}
= paginate @ticks

app/views/characters/profile.html.haml
%p#notice= notice

= breadcrumbs welcome_page_link, @character.name

.panel.panel-default
  %table.table.table-striped.table-rounded
    %tr
      %td{:rowspan => "2", :style => "width: 148px"}
        = character_image(@character.id)
        = link_to corporation_image(@character.corporation_id, 64), corporation_path(@character.corporation_id)
      %td= @character.name
      %th.numeric Total ISK Earned
      %th.numeric Total Rat Kills
      %th.numeric Average Tick
      %th.numeric Favourite Faction
    %tr
      %td= link_to @character.corporation.name, corporation_path(@character.corporation_id)
      %td.numeric= number_to_isk_short @character.total_isk
      %td.numeric= number_with_delimiter @character.total_kills
      %td.numeric= number_to_isk_short @character.average_tick
      %td.numeric
        = corporation_image @character.favourite_faction['corporation_id']
        = @character.favourite_faction['name']
    %tr
      %td{:colspan => "2"}
      %th.numeric Total Missions Run
      %th.numeric Favourite Mission Level
      %th.numeric Total DED Sites Run
      %th.numeric Favourite DED Site
    %tr
      %td{:colspan => "2"}
        = image_tag('awards/gold.png', style: 'height: 32px')
        = link_to awards_path(@character), class: 'btn btn-sm' do
          .label.label-success
            NEW!
          &nbsp;
          Awards
          
      %td.numeric= number_with_delimiter @character.missions_run
      %td.numeric= mission_level_label @character.favourite_mission_level
      %td.numeric= number_with_delimiter @character.ded_sites_run
      %td.numeric
        = faction_image @character.favourite_ded_site['ded_faction_id']
        = ded_site? @character.favourite_ded_site

.row
  .col-sm-4
    = render partial: 'earnings_by_day', locals: { caption: 'Earnings - Last 5 Days', more: true }
  .col-sm-4
    = render partial: 'top_ticks', locals: { caption: 'Top 5 Ticks', more: true }
  .col-sm-4
    = render partial: 'valuable_rats',  locals: { caption: 'Top 5 Rats Bounty', more: true }

%table.table.table-striped
  %caption
    Last 5 Ticks
    %span.pull-right= link_to 'More', character_journal_path(@character)
  %thead
    %tr
      %th.icon
      %th.timestamp Timestamp
      %th.details Details
      %th
      %th.numeric Amount
  %tbody
    - @ticks.each do |record|
      %tr
        %td= record_icon(record)
        %td= link_to record.ts, global_tick_path(record)
        %td= record_details(record)
        %td
          - record.kills.each do |kill|
            = kill_image(kill)
        %td.col-sm-1.numeric{ nowrap: :nowrap }= number_to_isk record.amount

app/views/characters/rats.html.haml
%p#notice= notice

= breadcrumbs welcome_page_link, character_link(@character), 'Top Rats Boundy'
= render partial: 'valuable_rats',  locals: { caption: 'Top Rats Bounty', more: false }
= paginate @valuable_rats

app/views/characters/ticks.html.haml
%p#notice= notice

= breadcrumbs welcome_page_link, character_link(@character), 'Top Ticks'
= render :partial => 'top_ticks', locals: { caption: 'Top Ticks' }
= paginate @top_ticks